---

# see http://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#local-playbooks

- name: install on localhost
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  roles:
    - {role: 'vimrc', tags: 'vim'}
    - {role: 'packages', tags: 'pkg'}
    - {role: 'rcfiles', tags: 'rc'}
