---

- name: update homebrew
  become: false
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: install brew formulas
  vars:
    formulas:
      - ack
      - adns
      - ansible
      - atk
      - autoconf
      - automake
      - bash-completion
      - bash-git-prompt
      - berkeley-db
      - cairo
      - coreutils
      - dos2unix
      - extract_url
      - fdupes
      - ffmpeg
      - fontconfig
      - freetype
      - fribidi
      - gdbm
      - gdk-pixbuf
      - gettext
      - git
      - git-flow
      - glib
      - gmp
      - gnupg
      - gnutls
      - gobject-introspection
      - gpg-agent
      - graphite2
      - gsettings-desktop-schemas
      - gtk+
      - gtk+3
      - gtk-mac-integration
      - harfbuzz
      - hicolor-icon-theme
      - hidapi
      - hopenpgp-tools
      - icu4c
      - jfrog-cli-go
      - jp2a
      - jpeg
      - jq
      - json-c
      - keychain
      - lame
      - lastpass-cli
      - libarchive
      - libassuan
      - libepoxy
      - libffi
      - libgcrypt
      - libgpg-error
      - libidn2
      - libksba
      - libmagic
      - libpng
      - libtasn1
      - libtiff
      - libtool
      - libu2f-host
      - libu2f-server
      - libunistring
      - libusb
      - libyaml
      - libyubikey
      - lua@5.1
      - md5sha1sum
      - mtr
      - ncftp
      - netcat
      - nettle
      - nmap
      - node
      - npth
      - oniguruma
      - openssl
      - openssl@1.1
      - p11-kit
      - pam-u2f
      - pam_yubico
      - pango
      - pcre
      - pinentry
      - pinentry-mac
      - pixman
      - pkg-config
      - popt
      - pth
      - pwgen
      - py2cairo
      - pygobject
      - pygtk
      - pyqt
      - python
      - python@2
      - qscintilla2
      - qt
      - rclone
      - readline
      - rpm
      - shared-mime-info
      - sip
      - sphinx-doc
      - sqlite
      - sshfs
      - tcpdump
      - telnet
      - tree
      - unison
      - wget
      - x264
      - xvid
      - xz
      - ykclient
      - ykman
      - ykpers
      - zstd
  homebrew:
    name: "{{ formulas }}"
    state: present
