---

- name: install the EPEL (Extra Packages for Enterprise Linux) repository
  become: true
  yum:
    pkg: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: install RHEL packages
  become: true
  vars:
    packagelist:
      - ack
      - git
      - python2
      - rpmdevtools
      - rpm-sign
      - screen
      - the_silver_searcher
      - tmux
      - util-linux
      - vim-common
      - vim-enhanced
      - vim-filesystem
      - vim-minimal
      - virt-what
  yum:
    pkg: "{{ packagelist }}"
    state: installed

- name: upgrade all packages
  become: true
  yum:
    name: '*'
    state: latest

