---

- name: install the EPEL (Extra Packages for Enterprise Linux) repository
  become: true
  yum:
    pkg: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: install RHEL packages
  become: true
  vars:
    packagelist:
      - ack
      - apg
      - bash-completion
      - bash-completion-extras
      - ctags-etags
      - git
      - git-lfs
      - hub
      - jq
      - lastpass-cli
      - pass
      - pwck
      - pwgen
      - python2
      - python36
      - python36-devel
      - python36-libs
      - python36-tools
      - rpmdevtools
      - rpm-sign
      - ruby
      - screen
      - the_silver_searcher
      - tree
      - tmux
      - util-linux
      - vim-common
      - vim-enhanced
      - vim-filesystem
      - vim-minimal
      - virt-what
  yum:
    pkg: "{{ packagelist }}"
    state: installed

