---

# install all my resource files

- name: create directory ${HOME}/.local/
  vars:
    HOME: "{{ ansible_env.HOME }}"
  file:
    path: "{{ HOME }}/.local/"
    state: directory
    mode: 0700

- name: install files from bashrc.d/ into ~/.local/bashrc.d/
  vars:
    LOCAL: "{{ ansible_env.HOME }}/.local/"
  copy:
    src: "files/bashrc.d/"
    dest: "{{ ansible_env.HOME }}/.local/bashrc.d/"
    mode: 0600
    directory_mode: 0700

# Deliberately *not* installing `gitconfig` because it's a bit messy. Need
# to template it out at some point in the future.
- name: install source files as "dotfiles"
  vars:
    HOME: "{{ ansible_env.HOME }}"
  copy:
    src: "files/{{ item }}"
    dest: "{{ HOME }}/.{{ item }}"
    mode: 0600
  loop:
    - ackrc
    - aliases
    - bashrc
    - bash_profile
    - cvsrc
    - perltidyrc
    - tmux.conf

